### ISSUE TITLE
Style Footer 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/libguides#3]

**Comment by mwardlb** [comment]
Uploaded BU WP footer HTML to LibGuides. Added some relevant CSS to dev.css. 
To Do: icon, responsiveness.

**Comment by tomhohenstein** [comment]
Fixed: icon 
Fixed: minor css differences 

The footer appears to behave like the wordpress footer, for better or worse. To make it responsive we will probably have to change the html to work with bootstrap grid (http://getbootstrap.com/examples/grid/)

**Comment by tomhohenstein** [comment]
I also made the css pretty :)

**Comment by tomhohenstein** [comment]
I think the footer styles are good to go for now - closing this
